### PR TITLE
Added misc/collapse.js and misc/form.js to the module to enable collapsibl fieldset on any page

### PR DESCRIPTION
**Pull request by irinaz**
Hi Shea, 

This is my first pull request on github, please correct me if I am doing something wrong.  
I have modified module to add two scripts to the module, rather than to the theme.   Let me what should I do next.

Thanks, Irina

After I started to work on feeds import feature I realized that this change creates an error -  "Uncaught ReferenceError: jQuery is not defined" and all jQuery is broken on the site.
Not sure how to deal with this :(

### CODE REVIEW

**Comment by irinaz** [comment]
I have added Basic Feed Import feature.  It works on my local install, I am not sure how to test it on real Jumpstart instance.  Also this feed requires user "import", and I do not know if it is possible to add creating a user to a feature. 

Thanks!

**Comment by irinaz** [comment]
@sherakama Please review

**Comment by sherakama** [comment]
Thanks for this Irina,

As per our discussion today please change the drupal_add_js functionality so that it is wrapped in hook_preprocess_page() function and only loads on the appropriate node types.

Please also remove any additional fields that the importers may need. Once completed I will review and add the importer feature to the installation profile.

Thank you for all your wonderful work.

**Comment by sherakama** [comment]
In regards to the feeds importer, please include the content type that the importer should be attached to. You may bundle it in the importer feature itself. Thanks.

**Comment by irinaz** [comment]
@sherakama 
Hi Shea, 
I believe that importer is working correctly now.  It is configured to import into Stanford Page, but it is not attached to any content type in basic settings. 

I hope that both changes are ready for your review and hopefully testing :)
Many thanks, Irina

**Comment by sherakama** [comment]
Thanks Irina, 

This is looking great. Just a couple of clean up items. 
1. Please remove the debug settings from the feeds importer. 
2. Please provide me a sample import URL so that I may test the actual importing. I am not sure what URL you have been using.

Thanks,
Shea

**Comment by irinaz** [comment]
Hi Shea, 
thanks a lot!  I removed debug settings - I did not realize that I sent them in the feature, and made couple more small changes. 

Here is example of import url 
https://studentaffairs.stanford.edu/basic-feed-data/580  

Thanks, Irina

**Comment by sherakama** [comment]
@irinaz 
Thanks for all your great work and patience. I made a few small formatting changes and have committed it into the project: https://github.com/SU-SWS/stanford_jumpstart_vpsa/commit/418e814e092aa04ea92e00026bc353f56d4d2ec0

**Comment by irinaz** [comment]
Thanks a lot, Shea,
I will learn how to format code better :)

thanks!

**Pull request closed without merging**
