### PR TITLE
Events import module

### PR DESCRIPTION
**Pull request by irinaz**
@sherakama
Hi Shea, 
I created a feature for that will allow to import events from Student affairs current site into Stanford Event content type.  Test import url is https://studentaffairs.stanford.edu/export-events/580.

This is alpha version - import for some fields, including event start/end date require more work on my side.  Can we do basic round of testing on https://sites.stanford.edu/jumpstart-vpsatest2/ to make sure that basic functionality works?

Thanks, Irina

### CODE REVIEW

**Comment by sherakama** [comment]
@irinaz,

Thanks for putting in this pull request. Unfortunately I cannot merge this in as it has merge conflicts. There have been updates to the repository since you have last worked on it. Please make sure you pull in the latest changes from the SU-SWS repository and fix any conflicts. 

To pull in the latest changes you will need to add SU-SWS as another 'remote'
1. git remote add sws git@github.com:SU-SWS/stanford_jumpstart_vpsa.git
2. git fetch sws
3. git pull sws 7.x-1.x
4. Fix any merge conflicts
5. Push back up to your 'remote' eg: git push origin 7.x-1.x

That should be enough so that the pull request page allows me to merge this request. 

Thanks,
Shea

**Comment by irinaz** [comment]
@sherakama 
Shea, thank you very much for detailed instructions - I hope that I completed them correctly and did not make any damage in SWS repo :).  
Thanks, Irina

**Comment by sherakama** [comment]
Thanks for this @irinaz, 

I have tested the importer on a build and it looks like it is close but needs some work. Currently, only the title, location, and body fields are being imported. Please revise the date and rsvp fields. Please also disable debug. 

As a side note, only approved complete work will be merged into the project. You will have to test this work elsewhere. 

Good stuff!

Thanks,
Shea

**Comment by irinaz** [comment]
Thanks, will do today asap.

BTW, I am testing new instance now, have some questions on new workflow.

Thanks, Irina

**Comment by irinaz** [comment]
@sherakama 
Hi Shea,

I have  changed settings for start date import and removed some content 
fields -  I will need to discuss with Joy how she wants to bring 
information into new site for the fields that do not map directly.

I am not sure how to bring in event end date properly - it will take me 
some time to figure out, maybe we do not need it for past events.

Please let me know if I need to make other changes in order to move this 
feature to testing and production for Monday review.

Thanks, Irina

**Comment by sherakama** [comment]
Hello Irina, 

This works much better. Thank you for making those revisions. I will merge it into the project now. Please note that it will not make it into monday's review as I do not want to rebuild over the test site at this time. We will go over the site as is on monday and your importer will make it into the next round of testing.

Thank you very much.

**Comment by irinaz** [comment]
@sherakama 
Shea, thanks a lot!
I will try to have news importer ready so we can review both of them together. 
Have a good weekend, 
thanks, Irina

**Pull request merged**
