### PR TITLE
Fix "Warning: sort() expects parameter 1 to be array, null given" error

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Fixes an error: ` Warning: sort() expects parameter 1 to be array, null given in stanford_jumpstart_vpsa_wysiwyg_editor_settings_alter() (line 36 of stanford_jumpstart_vpsa.module.`

# Needed By (Date)
- Not sure. March 15th?

# Urgency
- Not super-urgent. Fixes a PHP Warning

# Steps to Test

1. Clone `lbre-production` to local
2. Turn on error reporting
3. Go to `block/bgm-home-news--announcements-blo/edit`
4. See error message
5. Check out this branch
6. Go to `block/bgm-home-news--announcements-blo/edit`
7. Don't see error message

# Affected Projects or Products
- JSVPSA sites and LBRE sites

# Other Notes
Not sure if this should be fixed like this, or just put the `sort($settings['stylesSet']);` inside the `if ($context['profile']->format == "content_editor_text_format")` block. It's showing up on Full HTML pages.

### CODE REVIEW

**Comment by jbickar** [comment]
Also, can't figure out the CodeClimate warning. Should be 2 space indent, not 4.

**Comment by sherakama** [comment]
That warning appears because that key isn't available on the other formats. For Jumpstart we put this key in the check for content_editor_text_format:
https://github.com/SU-SWS/stanford_jumpstart/commit/5e4d4f52b7542926e4b1af9bee3c638bcda52ba9#diff-b6b5f747411d0dec50ba8b4e1ce900a7R33

We should probably do the same here.

**Comment by jbickar** [comment]
And still do a check for `array_key_exists()` as well?

**Comment by sherakama** [comment]
The key check isn't needed once it is wrapped in the if statement as line 17 would create that index key if it didn't exist.

**Comment by jbickar** [comment]
Right.

**Comment by sherakama** [comment]
Nice work. Thanks for tracking this down.

**Pull request merged**
